spring:
    datasource:
      url: jdbc:mysql://localhost:3306/configtest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 100714
      driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
      mode: HTML
      cache: false

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.neo.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*Dao.xml

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index

