server:
  port: 8088
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    # 消息发送确认回调 是否到达交换机和队列
    publisher-confirms: true
    publisher-returns: true
    # 消息接收确认回调 是否被消费
    listener:
      simple:
        acknowledge-mode: manual
